### ISSUE TITLE
CFDB Dataset

### ISSUE THREAD

**Issue by Hobeom** [PixelWeaver/ForestFireSegmentation#1]
http://cfdb.univ-corse.fr/ is no longer available.
Can I ask you to download the dataset?

**Comment by chamecall** [comment]
> http://cfdb.univ-corse.fr/ is no longer available. Can I ask you to download the dataset?

Hi dear, have you managed to obtain the dataset?

**Comment by cycnb233** [comment]
> > http://cfdb.univ-corse.fr/ is no longer available. Can I ask you to download the dataset?
> 
> Hi dear, have you managed to obtain the dataset?



> 

Did you download that dataset?

**Comment by PixelWeaver** [comment]
Hello @HoBeom @chamecall  @cycnb233 ! 

The URL might have changed, see here : [https://cfdb.univ-corse.fr/index.php]( https://cfdb.univ-corse.fr/index.php).

Before being to download, you'll have to apply for an access which is pretty straightforward, see [https://cfdb.univ-corse.fr/demarches_page_137_menu,3.htm](https://cfdb.univ-corse.fr/demarches_page_137_menu,3.htm).

**Comment by Hobeom** [comment]
Unfortunately, the dataset site seems to be inaccessible in our country. 
It is accessible through a VPN, but it is difficult to download because it cannot receive a lot of capacity.
